### ISSUE TITLE
Vertical moving platform and player seperation

### ISSUE THREAD

**Issue by approboGames** [britzl/platypus#11]
Player 'Leaves' vertical platform on way down even though gravity is set to a sufficient level as to keep player grounded on the platform.

To recreate:
In the example project set the Duration in moving_platform_3 to 2.5 then jump on it.

**Comment by britzl** [comment]
We're adding synchronous ray casts which should improve on this situation. I'll look into this again when that feature has been released.

**Comment by britzl** [comment]
Solved in latest release
