### ISSUE TITLE
onewayplatform (weird behavior) gets stuck at groundcontact

### ISSUE THREAD

**Issue by doble-d** [britzl/platypus#17]
![RECORDING](https://user-images.githubusercontent.com/14228267/67875772-74376200-fafc-11e9-8906-295f93b5d131.gif)

I was messing aroung with onewayplatforms but it seems I can't jump past them, I'm using the example code from the repo, this is the platypus.config

```lua
self.platypus = platypus.create({
    collisions = {
        separation = platypus.SEPARATION_SHAPES,
        groups = {
            [hash("ground")] = platypus.DIR_ALL,
            [hash("onewayplatform")] = platypus.DIR_DOWN,
            [hash("onewaydoor")] = platypus.DIR_LEFT,
        },
        left = 22.5, right = 22.5, top = 21.5, bottom = 23.5, offset = vmath.vector3(0, -4, 0)
    },
    gravity = -800,
    max_velocity = 580,
    allow_double_jump = true,
    allow_wall_jump = true,
    allow_wall_slide = true,
    wall_slide_gravity = -50,
})
```

**Comment by britzl** [comment]
Ah, hmm, yes, that does indeed not look as expected. I guess the expected behavior is to actually continue the jump? I'm able to reproduce this myself and will look into it today.
