### ISSUE TITLE
after loosing wall contact wall_slide_gravity still applies

### ISSUE THREAD

**Issue by marconett** [britzl/platypus#22]
with `allow_wall_jump = true` and `allow_wall_slide = true`, after loosing wall contact, `wall_slide_gravity` still applies (see gif).
doesn't affect me, just noticed it.

![92458583-e15c5f00-f1c5-11ea-9cbe-b122c8efe9c2](https://user-images.githubusercontent.com/3315507/92583779-1f738480-f293-11ea-86b8-35a6c85724c7.gif)

**Comment by britzl** [comment]
Thanks for reporting. Will take a look soon.
