### ISSUE TITLE
Unable to change length of collision RAYCAST at runtime

### ISSUE THREAD

**Issue by depstr1** [britzl/platypus#28]
[The Cyber Platypus issue report.zip](https://github.com/britzl/platypus/files/13450745/The.Cyber.Platypus.issue.report.zip)

I am trying to create Crouch mechanism which requires changing Collision Raycast length at runtime
 But when i manually change is_crouching variable ( true or false) and then run the game everything works fine  ( raycast's length is as expected) 
BUT when i try to change this from player script at runtime ( on input : Crouch) ,   the crouch state in platypus.lua changes well while the actual Raycast's length donot .

Seems like the platypus script decides the Raycast's length  at initializing only .

i made following changes to platypus.lua for this mechanism :

Declared variable for storing Crouching state at LINE 10:

![Screenshot 2023-11-23 091056](https://github.com/britzl/platypus/assets/149413636/adce2398-dde4-4cfe-b93a-f5a7c1a6b60a)

parameter for length of raycast during crouching state :

![Screenshot 2023-11-23 091159](https://github.com/britzl/platypus/assets/149413636/1f3a237f-5b56-47e2-8b9f-c9729eeba0f4)

using the crouch state to decide when to use which length  :

![Screenshot 2023-11-23 091248](https://github.com/britzl/platypus/assets/149413636/22f96272-2f22-4467-88dc-5debb6a222a5)

**Comment by britzl** [comment]
It is possible to change the rays by calling:

```lua
local p = platypus.create(...)
p.set_collisions({ left = 4, right = 4, top = 6, bottom = 6 })
```

**Comment by depstr1** [comment]
Thank you so much :) @britzl
